import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Icon } from 'react-native-elements';
import { colors, typography, spacing, borderRadius } from '../theme';

export default function TermsScreen() {
  const renderSection = (title: string, content: string) => (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionContent}>{content}</Text>
    </View>
  );

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={true}
      >
        <View style={styles.lastUpdated}>
          <Text style={styles.lastUpdatedText}>Last Updated: December 2024</Text>
        </View>

        <View style={styles.introduction}>
          <Text style={styles.introText}>
            By accessing or using HermeSpeed, you agree to be bound by these Terms of Service. 
            If you do not agree, please do not use our services.
          </Text>
        </View>

        {renderSection(
          "1. Service Description",
          "HermeSpeed provides AI-powered analysis and summaries of publicly available SEC filings, including 10-K annual reports, 10-Q quarterly reports, 8-K current reports, and S-1 registration statements.\n\n" +
          "We cover approximately 600 companies from the S&P 500 and NASDAQ 100 indices, processing filings within minutes of their publication on the SEC EDGAR database."
        )}

        {renderSection(
          "2. CRITICAL: Not Financial Advice",
          "IMPORTANT DISCLAIMER: HermeSpeed is an INFORMATION SERVICE ONLY. We provide analysis and summaries of SEC filings for informational and educational purposes.\n\n" +
          "HermeSpeed does NOT:\n" +
          "• Provide investment advice or recommendations\n" +
          "• Suggest buying or selling any securities\n" +
          "• Offer financial planning or advisory services\n" +
          "• Guarantee investment returns or outcomes\n\n" +
          "All investment decisions are solely your responsibility. You should consult with qualified financial professionals before making any investment decisions.\n\n" +
          "We are NOT a registered investment advisor, broker-dealer, or financial planner."
        )}

        {renderSection(
          "3. Subscription Plans",
          "HermeSpeed offers the following subscription plans:\n\n" +
          "• Free Plan: Limited to 2 filing views per day\n" +
          "• Pro Plan ($39/month or $390/year): Unlimited access\n\n" +
          "Subscriptions are billed in advance. You may cancel anytime through your account settings. Upon cancellation, Pro access continues until the end of your current billing period.\n\n" +
          "No refunds are provided for partial months or early cancellation."
        )}

        {renderSection(
          "4. Data Accuracy and Limitations",
          "While we strive to provide accurate analysis, HermeSpeed makes NO WARRANTIES regarding:\n\n" +
          "• Accuracy or completeness of AI-generated analysis\n" +
          "• Timeliness of filing detection or processing\n" +
          "• Absence of errors in data extraction\n" +
          "• Service availability or uptime\n\n" +
          "Our AI analysis is generated by large language models which may occasionally produce inaccurate or incomplete summaries. Always refer to the original SEC filing for authoritative information."
        )}

        {renderSection(
          "5. User Accounts",
          "To access HermeSpeed, you must create an account. You are responsible for:\n\n" +
          "• Maintaining confidentiality of your credentials\n" +
          "• All activities under your account\n" +
          "• Providing accurate information\n" +
          "• Notifying us of unauthorized use\n\n" +
          "You must be at least 18 years old to use HermeSpeed."
        )}

        {renderSection(
          "6. Acceptable Use",
          "You agree NOT to:\n\n" +
          "• Use the service for illegal purposes\n" +
          "• Attempt unauthorized access to our systems\n" +
          "• Share your account credentials\n" +
          "• Use automated tools without permission\n" +
          "• Resell or redistribute our content\n" +
          "• Manipulate or interfere with our services"
        )}

        {renderSection(
          "7. Intellectual Property",
          "HermeSpeed and its AI-generated analysis are proprietary to [Legal Entity Name]. Our analysis, summaries, and platform features are protected by copyright and other intellectual property laws.\n\n" +
          "You may not reproduce, redistribute, or create derivative works from our content without written permission."
        )}

        {renderSection(
          "8. Limitation of Liability",
          "TO THE MAXIMUM EXTENT PERMITTED BY LAW:\n\n" +
          "HermeSpeed shall NOT be liable for any:\n" +
          "• Investment losses or financial damages\n" +
          "• Indirect, incidental, or consequential damages\n" +
          "• Loss of profits, data, or business opportunities\n" +
          "• Damages arising from use or inability to use our service\n\n" +
          "Our total liability shall not exceed the amount you paid us in the 12 months prior to the claim.\n\n" +
          "Some jurisdictions do not allow liability limitations, so these may not apply to you."
        )}

        {renderSection(
          "9. Termination",
          "We may suspend or terminate your account at any time for:\n\n" +
          "• Violation of these Terms\n" +
          "• Fraudulent or illegal activity\n" +
          "• Non-payment of subscription fees\n" +
          "• Any reason at our sole discretion\n\n" +
          "Upon termination, your right to use HermeSpeed ceases immediately."
        )}

        {renderSection(
          "10. Privacy",
          "Your use of HermeSpeed is subject to our Privacy Policy. By using our service, you consent to our data practices as described in the Privacy Policy."
        )}

        {renderSection(
          "11. Changes to Terms",
          "We may update these Terms at any time. Material changes will be notified via email or through the platform. Continued use after changes constitutes acceptance of the updated Terms."
        )}

        {renderSection(
          "12. Governing Law",
          "These Terms are governed by the laws of [Jurisdiction]. Any disputes shall be resolved in the courts of [Jurisdiction].\n\n" +
          "If any provision is found unenforceable, the remaining provisions shall continue in full effect."
        )}

        {renderSection(
          "13. Contact",
          "For questions about these Terms:\n\n" +
          "Email: legal@hermespeed.com\n" +
          "Support: support@hermespeed.com\n\n" +
          "Legal Entity: [Legal Entity Name]\n" +
          "Address: [To be determined]"
        )}

        <View style={styles.agreement}>
          <View style={styles.agreementBox}>
            <Icon name="info" type="material" size={20} color={colors.primary} />
            <Text style={styles.agreementText}>
              By using HermeSpeed, you acknowledge that you have read, understood, 
              and agree to be bound by these Terms of Service.
            </Text>
          </View>
        </View>

        <View style={{ height: spacing.xxl }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
  },
  lastUpdated: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
  },
  lastUpdatedText: {
    fontSize: typography.fontSize.sm,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  introduction: {
    backgroundColor: colors.primaryLight + '10',
    padding: spacing.lg,
    borderRadius: borderRadius.md,
    marginBottom: spacing.xl,
  },
  introText: {
    fontSize: typography.fontSize.base,
    color: colors.text,
    lineHeight: 24,
    textAlign: 'center',
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text,
    marginBottom: spacing.md,
  },
  sectionContent: {
    fontSize: typography.fontSize.base,
    color: colors.text,
    lineHeight: 24,
    textAlign: 'justify',
  },
  agreement: {
    marginTop: spacing.xl,
    marginBottom: spacing.lg,
  },
  agreementBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.primary + '10',
    padding: spacing.lg,
    borderRadius: borderRadius.md,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
  },
  agreementText: {
    flex: 1,
    fontSize: typography.fontSize.sm,
    color: colors.text,
    lineHeight: 20,
    marginLeft: spacing.sm,
    fontWeight: typography.fontWeight.medium,
  },
});